version: '3'

services:
  tests:
    image: ghetto-avrae
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - mongo
      - redis
    environment:
      - DISCORD_OWNER_USER_ID=98765432109876543
      - MONGO_URL=mongodb://root:topsecret@mongo:27017
      - REDIS_URL=redis://redis:6379/0
      - DICECLOUD_USER
      - DICECLOUD_PASS
      - DICECLOUD_TOKEN
      - GOOGLE_SERVICE_ACCOUNT
      - TEST_GAMEDATA_BASE_PATH=tests/nlp/dist_do_not_commit/dist
    volumes:
      - "./shared:/app/shared"
      - "~/Documents/avrae/aws-kinesis-dataset-exploration-tool/data/1664301210-f5fa4da8-314f-4a45-966a-950e0682d4dd:/opt/dataset/"
      - "./logfile:/opt/logfile"
      - "./results.csv:/opt/results.csv"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: topsecret
    ports:
      - 58017:27017

  redis:
    image: redis:5
    ports:
      - 58379:6379